### ISSUE TITLE
bitrise amazon device farm runner there is no option to set device location

### ISSUE THREAD

**Issue by saiyenumula** [peartherapeutics/bitrise-aws-device-farm-file-deploy#19]
![Screen Shot 2019-10-03 at 11 23 31 PM](https://user-images.githubusercontent.com/47869034/66196646-c1372e00-e64d-11e9-9b90-ada4998ad8b9.png)
![Screen Shot 2019-10-03 at 11 24 45 PM](https://user-images.githubusercontent.com/47869034/66196664-c72d0f00-e64d-11e9-87ea-08a6b5f2a850.png
here I have attached the screenshot which I want in Bitrise amazon device farm runner to set the device location and environment.as my app works for only particular location(Los angeles).

Below option should populate in Amazon Device farm runner:
1.Set Location
2.Select env (Standard or Custom environment)

**Comment by fadookie** [comment]
Sounds good. I'm not actively developing this step anymore, but feel free to send a PR.

**Comment by saiyenumula** [comment]
hey @fadookie someone has already done PR please review it and  approve.

**Comment by elashpear** [comment]
Another user added the ability to specify the test-spec ARN to the device farm runner. They did not send me a PR and I had to hunt this down and [open the PR myself](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner) (elashpear is my work account.) They have since deleted their fork for some reason. I have not yet had time to test this PR to ensure it's backwards-compatible but I will try to get to this soon.

For now, I am closing this issue since you filed it against the file deploy step, not the runner step.
