### ISSUE TITLE
Would need to export the upload ARN to be able to chain with other command

### ISSUE THREAD

**Issue by otusweb** [peartherapeutics/bitrise-aws-device-farm-file-deploy#9]
It would be great to export the uploadARN to be able to chain this step with other step to start a run

`envman add -k AWS_TEST_BUNDLE_IPA_ARN -v $uploadARN`

**Comment by fadookie** [comment]
@otusweb good idea. please send a PR (also make sure to quote the variable.) In [the test runner step](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/issues), I think the way this should be handled is with an optional `test_package_arn` input. If it's not present, it would fall back to its current behavior of looking up the most recent upload with the provided `test_package_name`. So `test_package_name` should also be made optional, although the step would fail if neither was provided.

Would you be willing to make a PR for this?
In our current use case, we have separate repos/ci jobs for deploying our test package and for actually running the tests which is why my initial implementation doesn't have this sort of wiring.

**Comment by otusweb** [comment]
If i get some spare time, i might. The problem i thought about (for which i don't have a solution) is how to handle multiple step that create an upload. There need to be a way to know the ARN for the test package upload and for the app upload. Any idea?

**Comment by fadookie** [comment]
Bitrise CLI just added the ability to re-name an exported envvar from a
step.

**Comment by otusweb** [comment]
That might be a good way. unfortunately, I don't have a project that needs this right now, so i won't get to it any time soon.
